pull_request_rules:
    - name: Merge all pull requests
      conditions:
        - or:
            - files=Cargo.toml
            - files=Cargo.lock
      actions:
         merge:
           method: merge
