on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Enable auto-merge
        if: startsWith(github.repository, 'seyedeliasfakoorian/')
        uses: reitermarkus/automerge@634d0a4b51134c163eee182ac9aa79133eb33e8d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
          squash-commit-title: ${pull_request.title} (#${pull_request.number})
          squash-commit-message: '\n'
          pull-request: ${{ github.event.inputs.pull-request }}
          pull-request-author-associations: MEMBER,OWNER
